CREATE TABLE role(id INTEGER AUTO_INCREMENT PRIMARY KEY , name VARCHAR (20) NOT NULL );
CREATE TABLE user(id INTEGER AUTO_INCREMENT PRIMARY KEY , login VARCHAR (40) NOT NULL UNIQUE ,email VARCHAR (40) NOT NULL UNIQUE ,  password INTEGER not NULL ,
  roleId INTEGER NOT NULL REFERENCES role(id), fullname VARCHAR (120) NOT NULL, phone VARCHAR (20) NOT NULL,
   info VARCHAR(2048), status BOOLEAN DEFAULT FALSE);
CREATE TABLE topic(id INTEGER AUTO_INCREMENT PRIMARY KEY , name VARCHAR (360) NOT NULL );
CREATE TABLE chat(id INTEGER AUTO_INCREMENT PRIMARY KEY , topicId INTEGER NOT NULL REFERENCES topic(id) ON DELETE CASCADE,name VARCHAR (360) NOT NULL );
CREATE TABLE message(id INTEGER AUTO_INCREMENT PRIMARY KEY , chatId INTEGER NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
userId INTEGER NOT NULL REFERENCES user(id) ON DELETE SET NULL, text VARCHAR (2048) NOT NULL, sent DATE NOT NULL);